// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "options_anim_cells.inc.c"

struct Animation anim_options_banner[] = {
    /* 000 */ { options_cel001, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_options_select_stereo[] = {
    /* 000 */ { options_cel002, 2 },
    /* 001 */ { options_cel003, 2 },
    /* 002 */ { options_cel004, 2 },
    /* 003 */ { options_cel005, 2 },
    /* 004 */ { options_cel006, 40 },
    /* 005 */ END_ANIMATION,
};

struct Animation anim_options_select_mono[] = {
    /* 000 */ { options_cel008, 2 },
    /* 001 */ { options_cel009, 2 },
    /* 002 */ { options_cel010, 2 },
    /* 003 */ { options_cel011, 2 },
    /* 004 */ { options_cel012, 40 },
    /* 005 */ END_ANIMATION,
};

struct Animation anim_options_select_data_clear[] = {
    /* 000 */ { options_cel014, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_options_desc_box[] = {
    /* 000 */ { options_cel019, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_options_cursor_barista[] = {
    /* 000 */ { options_cel016, 4 },
    /* 001 */ { options_cel017, 4 },
    /* 002 */ { options_cel018, 4 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_options_off_stereo[] = {
    /* 000 */ { options_cel007, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_options_off_mono[] = {
    /* 000 */ { options_cel013, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_options_off_data_clear[] = {
    /* 000 */ { options_cel015, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_options_warning_box[] = {
    /* 000 */ { options_cel020, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_options_cursor_default[] = {
    /* 000 */ { options_cel022, 4 },
    /* 001 */ { options_cel023, 30 },
    /* 002 */ { options_cel021, 4 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_options_rshoulder[] = {
    /* 000 */ { options_rshoulder_0, 1 },
    /* 001 */ { options_rshoulder_2, 1 },
    /* 002 */ { options_rshoulder_4, 1 },
    /* 003 */ { options_rshoulder_5, 1 },
    /* 004 */ { options_rshoulder_6, 1 },
    /* 005 */ END_ANIMATION,
};

struct Animation anim_options_lshoulder[] = {
    /* 000 */ { options_lshoulder_0, 1 },
    /* 001 */ { options_lshoulder_1, 1 },
    /* 002 */ { options_lshoulder_2, 1 },
    /* 003 */ { options_lshoulder_3, 1 },
    /* 004 */ { options_lshoulder_4, 1 },
    /* 005 */ END_ANIMATION,
};

